version: '3.8'

services:

  db:
    build: ./db
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${DB_user}"
      POSTGRES_PASSWORD: "${DB_password}"
      POSTGRES_DB: "${DB_database}"
    volumes:
      - ./bd/data:/var/lib/postgresql/data # if you won't save data base or read
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  scrapinghub:
    image: scrapinghub/splash
    restart: always
    ports:
      - 8050:8050